### ISSUE TITLE
No-change steps outputted in chain

### ISSUE THREAD

**Issue by Untellable** [gerrymandr/RunDMCMC#101]
When no change is made in a step (usually bc single flip rejects via wes's magical code), it doesn't count as a step in terms of total_steps but it does output this step as part of the chain, making for an unnecessarily large chain. The chain shouldn't include no-change steps.

**Comment by Untellable** [comment]
To clarify, the inconsistency I found is that running a for loop through chain will yield more elements than total_steps. The difference is ~10x for propose_random_flip bc it often returns no change, but other proposals are also slightly off (ex: total_steps = 100 but chain has 102 or 103 elements). The small difference is probably due to something in the startup. 
Note: you have to actually loop through the elements of chain to check this bc. len(chain) is overidden to return total_steps rather than the actual length of chain.

**Comment by Untellable** [comment]
Having looked more into it I realized the problem is that the chain returns no-change steps but doesn't increment (in __next__ in chain). So we have to make the decision on whether to not increment and not return (in which case we'll lose the uniform sampling nature of the single_random_flip that wes implemented) or both increment and return in which case many total_steps will no longer represent the number of actual changes bc. many of the steps will be no-change. Or find some way of making it modular to choose between the two options.

**Comment by maxhully** [comment]
I think I know what's going on. I added an early return statement in the MarkovChain __next__ method for the case when the chain takes a self loop, to avoid re-checking validity. But I forgot to increment self.counter there. So we should add that before the return.

**Comment by maxhully** [comment]
Oh! Looks like you found it while I was typing.

We should increment and return. The no-change steps are indeed actual steps - they are just the self-loop steps to the same state, which are there to make the chain reversible. So we won't have total_steps distinct steps, but this should be the expected behavior when the proposal function proposes these self loop steps. Does that make sense? Daryl explains it best...

**Comment by Untellable** [comment]
Yeah that was my thought. The only problem with that is that it makes the chain performance somewhat unreliable with the single_random_flip. Bc ~90% of the changes are no-change, if total_steps = 1000 you'll only get around 100 actually different steps. I'm not sure if we'd want that.

**Comment by Untellable** [comment]
Sorry just saw your second message. That seems reasonable to me, I just wanted to make sure that's what we wanted. I'll make the pull request

**Comment by maxhully** [comment]
Thanks for taking care of it!
