### ISSUE TITLE
Allow checking if yielded state was accepted

### ISSUE THREAD

**Issue by rwbogl** [gerrymandr/RunDMCMC#103]
Currently, the chain yields all valid proposed states. There is no way for a user to check if a state yielded by the chain iterator was accepted. (We know if it's _valid_, but not accepted.)

**Comment by maxhully** [comment]
(We resolved this on slack)

**Comment by rwbogl** [comment]
I believe that the conclusion on Slack was that the chain doesn't do this. I think that it would be worthwhile to add this, as otherwise users must duplicate the work of the acceptance function in their chain iterations.

**Comment by maxhully** [comment]
Added this in #214 .
