### ISSUE TITLE
Our relative paths to testData assume the working directory is RunDMCMC/rundmcmc

### ISSUE THREAD

**Issue by maxhully** [gerrymandr/RunDMCMC#110]
If a user working in a different directory and imports rundmcmc, they won't be able to use our `PA_partition()` for data. I discovered this when I moved the metagraph degree examples into a RunDMCMC/examples folder and tried to run it. I'm sure there's a canonical solution to this problem.

**Comment by msarahan** [comment]
A more canonical way of doing things is to put it in a known folder and use relative paths to that folder.  For example, in tests, I often have this pattern:

tests/data/somefile.txt
tests/sometest.py

in sometest.py, I use:

```
import os
data_folder = os.path.join(os.path.dirname(__file__), 'data')
data_file = os.path.join(data_folder, "somefile.txt")
```

If you need data to be available after importing rundmcmc, you need to nest it underneath the rundmcmc inner folder.  It can be kind of painful to do this with python.  https://stackoverflow.com/questions/12191339/add-data-files-to-python-projects-setup-py

**Comment by maxhully** [comment]
Thanks Mike!

Ultimately, I guess, rundmcmc shouldn't actually be responsible for bring the shapefiles. So this issue is low-priority until anyone at VRDI runs into an issue with it.

**Comment by maxhully** [comment]
I think our ultimate policy should be that RunDMCMC doesn't bring the data with it. Now that we have generated VTD graphs in [vtd-adjacency-graphs](https://github.com/gerrymandr/vtd-adjacency-graphs) for (almost) every state, we can make that the official policy without leaving our users high and dry. So I'll close this as a non-issue now.

**Comment by rwbogl** [comment]
@maxhully `PA_partition()` uses our test data and is cited in every example. Do you see that function being removed in a "final" version?
