### ISSUE TITLE
Inconsistent labeling

### ISSUE THREAD

**Issue by Untellable** [gerrymandr/RunDMCMC#147]
In validity.py, L1_reciprocal_polsby_popper references partition['polsby_popper_updater'], but defaults.PA_partition() the polsby popper variable is instantiated as 'polsby_popper'.

**Comment by maxhully** [comment]
I just did a code-wide search for `'polsby_popper_updater'` and it looks like the changes we made this morning have eliminated it from the code base. So hopefully this should be resolved by pulling the latest changes.
