### ISSUE TITLE
Save graph after building from config in __main__

### ISSUE THREAD

**Issue by rwbogl** [gerrymandr/RunDMCMC#150]
I don't think that the current main saves its adjacency graph after it builds it. This makes it really tedious to rerun the chain if there was a problem with the config file, but the shapefile was fine. Can we add a function to save the graph after it's created, then give people tips on how to reload it? `__main__` might need some modifications to check for files already existing, or something like that.

**Comment by drdeford** [comment]
The template_main.py file in my pull request does this by default.

**Comment by rwbogl** [comment]
Good -- I think that should be default behavior. Unfortunately that won't help people running the chain through the GUI right now.

**Comment by rwbogl** [comment]
Feature added in #169.
