### ISSUE TITLE
local variable referenced before assignment exception

### ISSUE THREAD

**Issue by rwbogl** [gerrymandr/RunDMCMC#154]
From Patrick Giradet on slack:

![image](https://user-images.githubusercontent.com/13404951/42595947-f0f246cc-8521-11e8-857d-98c7a4ee3421.png)

>When I run chain (or at least the command I'm told to run upon closing the config GUI) I get this error. Is there something I missed?

**Comment by maxhully** [comment]
I saw this error this morning. The config file had an [EVALUATION_SCORES_LOG] section without having an [EVALUATION_SCORES] section. The variable `funcs` is set in an if-block that asks if 'EVALUATION_SCORES' is set. We should have a default `funcs` (would an empty list make sense?) that we set before the if-block to avoid this exception.

**Comment by rwbogl** [comment]
I just saw the same thing. The return variable is called `elist` when it's assigned later, so I assume that an empty list would be an appropriate default value. The list is eventually passed to whatever `output_vis_type` is assigned to, but I can't follow what that's supposed to be at a glance.

**Comment by drdeford** [comment]
Probably symptomatic of the broader GUI issue that it is definitely possible to generate non-functioning .ini files. For the current version this seems totally fine to me but something to think about when we freeze a version. 

 Planning to get the example configs in tomorrow, so people will have a starting place/something to compare their outputs to before running.

**Comment by rwbogl** [comment]
I added a quick fix to this problem in PR #153.

**Comment by rwbogl** [comment]
Closed by #153. Reopen if there are continued issues.

**Comment by zachlevitt** [comment]
Using the updated code, I am still getting this issue. See attached picture
<img width="854" alt="screen shot 2018-07-12 at 11 14 13 am" src="https://user-images.githubusercontent.com/39925238/42642446-e51fbdae-85c4-11e8-88f3-5d928dee3aa5.png">

**Comment by MuNaught** [comment]
Not sure if this is the right thread (I'm happy to open a new issue), but after pulling the latest version I'm still getting a similar error for the 'validators' variable: 
![validators_error](https://user-images.githubusercontent.com/9301226/42643880-35e6fc7c-85c8-11e8-8d00-5d141df10835.PNG)

Here's the config file used: 
[GRAPH_SOURCE]
gsource = C:/Users/pgirardet/Miniconda2/envs/vrdi/projects/yourstate/govt_VTDs/final_merged_shapefile.shp

[GRAPH_DATA]
id = ID
pop = POPULATION
cd = DISTRICT
area = tot_st_hou

[VALIDITY]
colrefuse_new_splits,10 = refuse_new_splits,10

[EVALUATION_SCORES]
col0 = efficiency_gap,dem_st_hou,rep_st_hou

[EVALUATION_SCORES_LOG]
colwrite_hists = write_hists

[SAVEFILENAME]
write_hists = hist.png
write_flips = json filename.json
write_p_values = report filename.txt

[MARKOV_CHAIN]
num_steps = 1000000
proposal = propose_random_flip
accept = always_accept

**Comment by rwbogl** [comment]
@MuNaught Mind opening a new issue for that? At a glance it looks like fixing one issue wouldn't fix both.

@zachlevitt When's the last time you pulled from master? That traceback looks like it's from an older version. (Older than about an hour ago, that is.) You might need to run `python3 setup.py develop` to make sure the changes are reflected.

**Comment by rwbogl** [comment]
I think that this is fixed. Reopen if the issue persists!
