### ISSUE TITLE
Error with histogram: Max must be larger than min in range parameter.

### ISSUE THREAD

**Issue by zachlevitt** [gerrymandr/RunDMCMC#165]
Getting this error when creating a histogram. 

Here is config file:

[GRAPH_SOURCE]
gsource = /Users/ZachLevitt/Desktop/RI/RI_precincts_ALL.shp

[GRAPH_DATA]
id = NAME
pop = US_Censu14
cd = CD
area = Shape__Are

[VOTE_DATA_SOURCE]
vsource = /Users/ZachLevitt/Desktop/RI/RI_precincts_ALL.shp
vsourceid = NAME

[VOTE_DATA]
col0 = perc_dem
col1 =  perc_rep

[VALIDITY]
col0 = no_vanishing_districts

[EVALUATION_SCORES]
col0 = efficiency_gap,perc_dem,perc_rep

[EVALUATION_SCORES_LOG]
colwrite_hists = write_hists

[SAVEFILENAME]
write_hists = hist1500.png
write_flips = json filename.json
write_p_values = report filename.txt

[MARKOV_CHAIN]
num_steps = 500
proposal = propose_random_flip
accept = always_accept

<img width="836" alt="screen shot 2018-07-12 at 1 53 32 pm" src="https://user-images.githubusercontent.com/39925238/42650699-18da2592-85db-11e8-95ad-6868d0582a76.png">

**Comment by rwbogl** [comment]
This happens because the array passed to the histogram functions contains `nan`'s. I'm not sure why or how to fix it yet.

**Comment by rwbogl** [comment]
I suspect that this is a data error. Specifically, I suspect that `nan`'s have crept in somehow. I added a possible fix to this in PR #176. If that gets merged, then `nan`'s will be loudly dropped when encountered.

**Comment by rwbogl** [comment]
Closed by #176. Reopen if issues persist.
