### ISSUE TITLE
'rundmcmc.validity' has no attribute 'no_more_disconnected'

### ISSUE THREAD

**Issue by zschutzman** [gerrymandr/RunDMCMC#167]
Using the "No More Disconnected" validator causes 
`AttributeError: module 'rundmcmc.validity' has no attribute 'no_more_disconnected'`

**Comment by rwbogl** [comment]
Have you pulled the most recent version of master? Did you install using `python3 setup.py develop` instead of `python3 setup.py install`?

**Comment by zschutzman** [comment]
Yes to all of the above.

**Comment by marybarker** [comment]
It's there--line 300, can you check your validity.py file and see if it was updated with the most recent pull?

**Comment by zschutzman** [comment]
I have it. I'll pull and try again later :)

**Comment by rwbogl** [comment]
@zschutzman Any resolution to this?

**Comment by zschutzman** [comment]
I cleared everything out, pulled again, and reinstalled and it's working now. Thanks!
