### ISSUE TITLE
DataFrame.itertuples is sensitive to column names

### ISSUE THREAD

**Issue by mahrud** [gerrymandr/RunDMCMC#177]
As it turns out, [`pandas.DataFrame.itertuples`](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.itertuples.html) is very sensitive about column names:

> The column names will be renamed to positional names if they are invalid Python identifiers, repeated, or start with an underscore. With a large number of columns (>255), regular tuples are returned.

This causes issues here:

https://github.com/gerrymandr/RunDMCMC/blob/339e6614f4d17317648dfbc442897bad98ccad3b/rundmcmc/make_graph.py#L48-L52

For instance, if a vote column contains a space or starts with a number, for instance `16SenDVote`, you get the following error:

```
AttributeError: 'Pandas' object has no attribute '16SenDVote'
```

Inspecting `row` yielded something like this:
```
Pandas(Index=0, GEOID10='32031002205', _2=26.176389376638202, _3=26.636492387822347)
```
Quick solution is to change the column names, but perhaps some sanitizing should be done when the config file is generated.

**Comment by rwbogl** [comment]
This is such a bizarre restriction. It comes from [this line](https://github.com/pandas-dev/pandas/blob/1a23779f09abc6ebf908d66ee88b973b767e2e3c/pandas/core/frame.py#L832) in the implementation of `itertuples()`.

>Quick solution is to change the column names, but perhaps some sanitizing should be done when the config file is generated.

Is there even a convenient way to detect when something isn't a valid identifier? For instance, how would we know that "16SenDVote" was converted to, say, "_1"? Maybe something like `any(col not in row.__dict__ for col in col_names)` could detect this.

Perhaps there's a not-too-complicated way to rewrite this while avoiding `itertuples()`.

**Comment by maxhully** [comment]
https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html might be of use.

**Comment by maxhully** [comment]
I think we could avoid itertuples by doing this.
1. Set the dataframe's index to be the id column
2.  Convert the columns to `{node: value}` dictionaries by calling (to_dict)[https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_dict.html],
3. Call `set_node_attributes` for each column.

**Comment by maxhully** [comment]
OK - I implemented the strategy I just described. I'll make a pull request tomorrow morning.
