### ISSUE TITLE
import alias conflict psutil and pysal

### ISSUE THREAD

**Issue by drdeford** [gerrymandr/RunDMCMC#181]
In datastore.py we have:
>import psutil as ps 

and in make_graph.py we have:
>import pysal as ps

**Comment by rwbogl** [comment]
Strictly speaking this isn't a problem, but it's confusing. I don't think that `ps` is a "standard" `psutil` import, so I'm fine changing it to something else.

**Comment by drdeford** [comment]
I agree it isn't going to make anything explode :) just something we should fix while cleaning up the namespaces and terminology.

**Comment by rwbogl** [comment]
For sure! `make_graph.py` is next on my "surface level" cleanup list, so I'll probably fix it in my next PR.
