### ISSUE TITLE
New ingest method makes discontiguous test graph

### ISSUE THREAD

**Issue by rwbogl** [gerrymandr/RunDMCMC#49]
When loading the Wyoming test data with the new ingest method in PR #29 on branch `simplify-ingest`, the districts are not initially contiguous. This can be reproduced by running `__main__.py` on that branch and noticing the infinite hang, or by inserting a `networkx.is_connected()` call in that file where appropriate.

This seems to be a conflict between the new method and the existing `add_data_to_graph()`. I think that the latter assumes that nodes are read in lock-step with the data, while the new ingester doesn't have a specified order from what I can tell.

If I have the issue right, I think that reading in graphs should change to acommodate the new `ingest()` behavior since it's much nicer. I'm not completely sure what the best way to do that is right now, though.

Ping @wtadler.

**Comment by maxhully** [comment]
We should make sure to write a unit test that catches this bug on Monday.

**Comment by rwbogl** [comment]
For whoever writes those tests: I have some basic contiguity unit tests in
my local copy of that branch, but none of them catch that issue. I would
guess that it's some coincidence in the test data that the IO isn't being
too careful about right now.

**Comment by rwbogl** [comment]
This was fixed in PR #54. I will close this after including some unit tests for the issue.

**Comment by rwbogl** [comment]
Tests added in PR #55. The discontiguous issue is no longer present.
