### ISSUE TITLE
error catch

### ISSUE THREAD

**Issue by marybarker** [gerrymandr/RunDMCMC#59]
At the moment, if the initial districting plan is not contiguous (more generally, fails validity check) then we get in a semi-infinite loop as any proposed change that doesn't fix the initial invalid issues also gets thrown out so the counter does not increment in the markovchain object.

**Comment by rwbogl** [comment]
This was how I caught the recent ingest issue. How do we determine the
difference between an infinite loop and very difficult to satisfy
validators?

I propose a "max tries per step" option, or maybe a "max tried steps total."

**Comment by marybarker** [comment]
Might work... I think in the version of Wes' code there was an option that was just that for validity the new plan had to at least not add violations in excess of the original plan(e.g. if a district is not contiguous to begin with, then can still run chain using it but stipulate that no discontinuities in other districts occurs, so essentially a running tally of bools for each district that doesn't change, or if it does, the right way)

**Comment by maxhully** [comment]
We could do the validity checks on the initial districting plan in the __init__ method of MarkovChain, and then raise an exception if it fails.

Then separately we can implement the smarter validity functions like Mary was saying.

**Comment by maxhully** [comment]
We now have the exception I mentioned, so I'll close this.
