### ISSUE TITLE
Updaters cannot reliably access previous updaters

### ISSUE THREAD

**Issue by rwbogl** [gerrymandr/RunDMCMC#64]
If updaters want to access the results of previous updaters, they must do so with a one-step "delay." This is because they access the `partition.field` attribute while it is being updated, meaning that they can't see new changes. In particular, updaters _cannot_ use the results of previously run updaters on the initial state.

As an example, I am currently working on a discrete Polsby-Popper updater. While `cut_edges` already tracks what edges are cutting across assignments, the D-PP updater can't use it on the first run, and can't compute the "real" score of any later proposed partition.

**Comment by rwbogl** [comment]
This seems particularly annoying, as even the Polsby-Popper score could be computed by relying on earlier-run statistics updaters collecting area and perimeter. (See #51.)

**Comment by maxhully** [comment]
The cut edges issue you identified is a huge problem! We could make cut_edges an attribute of Partition, move the updater computations (currently in merge()) into the init method of Partition, and give it the old partition as an argument. Like init would take self, parent_partition (say) and flips as arguments.

That probably wasn't super  clear. We can talk about it later this afternoon.

**Comment by rwbogl** [comment]
> We could make cut_edges an attribute of Partition, move the updater computations (currently in merge()) into the init method of Partition, and give it the old partition as an argument.

I'm worried that this is treating a symptom rather than the core problem. By that I mean that `cut_edges` is only a problem for this one updater, but other attributes could be problems for others.

Someone suggested that we could move certain "special updaters" into a "super-special updaters" step. My issue with this is that we already split updaters off from validators for basically the same reason. I'd like to hammer out some details for why this would be a "final solution" rather than another stop-gap.
