### ISSUE TITLE
Suggestion: accept() functions should take both the proposed next state and the current state as arguments

### ISSUE THREAD

**Issue by zschutzman** [gerrymandr/RunDMCMC#87]
For Metropolis-Hastings MCMC, acceptance is a function of some score of the current state and the proposed next state, so the line
https://github.com/gerrymandr/RunDMCMC/blob/3e6cde710e3287bf1d64d73a217ac9aace5fa967/rundmcmc/chain.py#L44
will need to look something like
           `if self.accept(self.state, proposed_next_state):`

in order to make that work.

**Comment by rwbogl** [comment]
Closing this as a non-issue for now. Feel free to reopen if needed.
